version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    target-branch: main
    ignore:
      - dependency-name: "org.apache.maven.plugins:maven-gpg-plugin"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: main